name: gigvora_mobile_shell
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  advertisement_flutter_addon:
    path: ../../Gigvora-Addons/Advertisement-Addon/Advertisement_Flutter_addon
  talent_ai_flutter_addon:
    path: ../../Gigvora-Addons/Ai-Headhunter-Launchpad-Addon/Ai-Headhunter-E_Launchpad-flutter_addon
  freelance_phone_addon:
    path: ../../Gigvora-Addons/Freelance-Addon/freelance_phone_addon
  webinar_networking_interview_podcast_flutter_addon:
    path: ../../Gigvora-Addons/Interactive-Addon/Webinar_networking_interview_and_Podcast_Flutter_addon
  pro_network_utilities_security_analytics:
    path: ../../Gigvora-Addons/Utilities-Addon/flutter_addon
  jobs_flutter_addon:
    path: ../../Gigvora-Addons/Jobs-Addon/Jobs_Flutter_addon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
